name: DEV repo CI/CD

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    plan:
        runs-on: ubuntu-latest
        environment: dev
        env: 
            PROJECT_SECRET: ${{ secrets.PROJECT_SECRET }}
            PROJECT_VARIABLE: ${{ vars.PROJECT_VARIABLE }}
        steps:
            - uses: actions/checkout@v3
            - name: Set ENV variable
              run: echo "ENV_NAME=dev" >> $GITHUB_ENV

            - name:  Running plan 
              run: |
                echo "Secret: $PROJECT_SECRET"
                echo "Variable: $PROJECT_VARIABLE"
    
    apply:
        runs-on: ubuntu-latest
        environment: dev
        needs: [plan]
        env: 
            PROJECT_SECRET: ${{ secrets.PROJECT_SECRET }}
            PROJECT_VARIABLE: ${{ vars.PROJECT_VARIABLE }}
        steps:
            - uses: actions/checkout@v3
            - name: Set ENV variable
              run: echo "ENV_NAME=dev" >> $GITHUB_ENV

            - name:  Running apply 
              run: |
                echo "Secret: $PROJECT_SECRET"
                echo "Variable: $PROJECT_VARIABLE"

